### ISSUE TITLE
Opus playback

### ISSUE THREAD

**Issue by toerb** [gpodder/gpodder-sailfish#33] opened 2015-03-28 15:19 UTC
Hello,
I am on version 4.4.0 and opus items wont play.
After clicking the play item in the UI nothing is happening.
Other mp3 items work just fine.

I mentioned this bug trying to play a file from this feed: http://freakshow.fm/feed/opus/

Best regards,
toerb

**Comment by thp** [comment] 2015-03-31 05:49
Yes, this needs to be supported in the platform middleware, and then should automatically be supported by gPodder:

https://together.jolla.com/question/5556/upgrade-gstreamer-to-support-opus-codec/

**Comment by thp** [comment] 2015-03-31 05:52
As an unsupported third party workaround, you could try this:

https://openrepos.net/content/sailfishlib/gst-plugins-bad-extra

**Comment by florianjacob** [comment] 2015-12-28 14:10
I can confirm opus playback via gpodder works flawlessly in SailfishOS 2.0.0.10. :grin:

**Comment by schmittlauch** [comment] 2017-02-20 00:01
@thp You can close this issue now. opus support is now present in SailfishOS and because of this in gPodder as well

**Comment by florianjacob** [comment] 2017-02-20 08:58
( @schmittlauch Meegons (and binaergewitter) ftw! :D )

**Comment by thp** [comment] 2017-02-20 09:03
Closing as per the recent comments.

**Closed by thp** 2017-02-20 09:03 UTC
