### ISSUE TITLE
[Wishlist] Headphone button / Bluetooth control

### ISSUE THREAD

**Issue by cy8aer** [gpodder/gpodder-sailfish#47] opened 2017-01-09 09:46 UTC
... like done in talefish right now.

**Comment by mase76** [comment] 2017-02-06 14:54
+1

**Comment by schmittlauch** [comment] 2017-02-20 00:03
I think this partly overlaps with #43 as, AFAIK, the system middleware controls apps via MPRIS

**Comment by schmittlauch** [comment] 2017-02-20 10:45
Duplicate of #6, can be closed @thp

**Closed** 2017-02-20 10:48 UTC
