### ISSUE TITLE
Can't add a specific podcast

### ISSUE THREAD

**Issue by jesxzkmdul8** [gpodder/gpodder-sailfish#198] opened 2024-08-06 06:44 UTC
I try to add a specific podcast ("19:04 - Inside Schalke"). I can search fosearchr it, but when I try to add it, I am redirected to the overview of my podcasts, but the podcast isn't added. I tried to add it in gPodder to verify that the podcast itself is not broken, and I can add it there. Maybe the ":" in the name is a problem? For information: SFOS 4.6.0.13 in Xperia 10 III, gPodder 4.16.3-1.

**Comment by Keeper-of-the-Keys** [comment] 2024-08-06 07:58
Hey I was unable to reproduce your issue on the emulator or on my phone (10ii)  I was able to add the podcast both via Apple and Podverse.

It did take a while to load over cellular data because there are many episodes while it is in this stage you have a "spinning circle" under a heading "Other".

If the problem persists can you look at the contents of `.cache/harbour-org.gpodder.sailfish/logs` and include a log from when you tried to add it here?

**Comment by jesxzkmdul8** [comment] 2024-08-06 09:38
I tried to add it from Podverse and from Apple, but it fails (YouTube doesn't find anything).
The log is empty, only for an information when I close the App ("Shutting down core"). In contrast, if I add any other podcast, the log contains 20kB of logs.

I also tried setting the phone to English ( normally German), but that doesn't change anything.

**Comment by Keeper-of-the-Keys** [comment] 2024-09-11 06:52
Hey can you see if the new version maybe gives you an error message?
If not it is possible to change the log level to more verbose but currently that involves changing a file, I'm considering adding a dropdown to settings for this.

**Comment by jesxzkmdul8** [comment] 2024-10-03 18:47
Sorry, somehow missed your question. The log still doesn't contain any information. But for some reason, the podcast is now added to the list. I guess the issue could be closed then?

**Comment by Keeper-of-the-Keys** [comment] 2024-10-05 21:37
Hey, since the issue seems to have resolved itself and was not reproducible I'm closing it.

**Closed by Keeper-of-the-Keys** 2024-10-05 21:37 UTC
Labels: triage
